var langMessages = {
  "zh-cn": {
    "s1": "完善信息",
    "s2": "邮箱",
    "s3": "验证",
    "s4": "已验证",
    "s5": "国家",
    "s6": "手机",
    "s7": "名",
    "s8": "姓",
    "s9": "性别",
    "s10": "选择",
    "s11": "出生日期",
    "s12": "完整地址",
    "s13": "城市",
    "s14": "邮政编码",
    "s15": "国家或地区",
    "s16": "我不是美国公民/我不是在美国出生",
    "s17": "交易相关[问题](http://baidu.com)",
    "s18": "我已阅读并理解上述问题",
    "s19": "我接受各项<span class='inject-url' id='http://m.bravely.cn/product/gold/aboutus/pdf/Client_Agreement.html'>条款条约</span>，<span class='inject-url'  id='http://m.bravely.cn/product/gold/aboutus/pdf/Privacy_Policy.html'>隐私政策</span>，<span class='inject-url' id='http://m.bravely.cn/product/gold/aboutus/pdf/RiskDisclosure_Warning_Notice.html'>风险披露</span>，以及<span class='inject-url' id='http://m.bravely.cn/product/gold/aboutus/pdf/Withdrawl_policy.html'>入金和出金政策</span>",
    "s20": "确认",
    "s21": "验证码已发送到&value&，请查看收件箱。验证码30分钟内有效。",
    "s22": "验证码",
    "s23": "重发",
    "s24": "取消",
    "s25": "要放弃填写吗？",
    "s26": "放弃",
    "s27": "继续完善",
    "s28": "现在您可以充值1000美元以下的金额。",
    "s29": "好的",
    "s30": "以下信息将用来验证您的身份，并帮助评估我们产品对您的适用性和可持续性。您的信息将始终保密。",
    "s31": "护照或身份证证明",
    "s32": "阅读证明文件要求，[查看详情]",
    "s33": "护照",
    "s34": "身份证",
    "s35": "上传护照",
    "s36": "上传身份证正面",
    "s37": "上传身份证背面",
    "s38": "上传中",
    "s39": "上传失败，请重新上传",
    "s40": "地址证明",
    "s41": "上传",
    "s42": "上一步",
    "s43": "下一步",
    "s44": "还差一步，就全部完成了",
    "s45": "地址证明要求",
    "s46": "文件类型：公用事业账单，或银行/信用卡对账单<br/>有效问卷必须包括：<br/>全名<br/>您的地址<br/>不超过3个月",
    "s47": "护照或身份证证明要求",
    "s48": "有效问卷必须包括：<br/>彩色照片<br/>全名<br/>出生日期<br/>有效日期<br/>官方证件号",
    "s49": "100%完成资料！",
    "s50": "审核中",
    "s51": "我们将尽快审核",
    "s52": "抱歉！未通过审核",
    "s53": "重新修改",
    "s54": "请验证你的邮箱",
    "s55": "请填写你的电话",
    "s56": "请填写你的名",
    "s57": "请填写你的姓",
    "s58": "请选择你的性别",
    "s59": "请选择你的出生日期",
    "s60": "请填写你的地址",
    "s61": "请填写你的城市",
    "s62": "请填写你的邮政编码",
    "s63": "请选择你的国家",
    "s64": "请上传护照",
    "s65": "请上传身份证正面",
    "s66": "请上传身份证背面",
    "s67": "请上传地址证明",
    "s68": "请输入验证码",
    "s69": "验证码错误",
    "s70": "验证成功",
    "s71": "请确认您已阅读并理解交易相关问题",
    "s72": "请确认是否接受各项款条约，隐私政策，风险披露，以及入金和出金政策",
    "s73": "请选择国家区号",
    "s74": "男",
    "s75": "女",
    "s76": "电话",
    "s77": "一月",
    "s78": "二月",
    "s79": "三月",
    "s80": "四月",
    "s81": "五月",
    "s82": "六月",
    "s83": "七月",
    "s84": "八月",
    "s85": "九月",
    "s86": "十月",
    "s87": "十一月",
    "s88": "十二月",
    "s89": "邮箱格式不正确",
    "s90": "现在您可以充值1000美元以下的金额。",
    "s91": "上传地址证明",
    "s7777": "姓名"
  },
  "en-us": {
    "s1": "Complete Profile",
    "s2": "Email",
    "s3": "Verify",
    "s4": "Varified",
    "s5": "Country",
    "s6": "Number",
    "s7": "First Name",
    "s8": "Last Name",
    "s9": "Gender",
    "s10": "Select",
    "s11": "Date of Birth",
    "s12": "Full Address",
    "s13": "City",
    "s14": "Zip Code",
    "s15": "Country or Region",
    "s16": "I am not a US Citizen / I was not born in the US.",
    "s17": "[Questions](http://baidu.com) about your trading",
    "s18": "I declare that I have read and understood above questions.",
    "s19": "I accept the <span class='inject-url' id='http://m.bravely.cn/product/gold/aboutus/pdf/Client_Agreement.html'>Terms &Conditions</span>, <span class='inject-url' id='http://m.bravely.cn/product/gold/aboutus/pdf/Privacy_Policy.html'>Privacy Policy</span> and <span class='inject-url'  id='http://m.bravely.cn/product/gold/aboutus/pdf/RiskDisclosure_Warning_Notice.html'>Risk Disclosure</span> and <span class='inject-url' id='http://m.bravely.cn/product/gold/aboutus/pdf/Withdrawl_policy.html'>Deposit&Withdrawal Policy</span>.",
    "s20": "Confirm",
    "s21": "The verification code has been sent to &value& , please check the inbox.The code will be valid within 30 minutes.",
    "s22": "Verification Code",
    "s23": "Resend",
    "s24": "Cancel",
    "s25": "Do you want to give up?",
    "s26": "Give Up",
    "s27": "Continue",
    "s28": "Now you can start trading now with up to USD 1000.",
    "s29": "OK",
    "s30": "The following information is used to verify your identity and to assess the appropriateness and suitability of our product to your profile. Your information is always kept confidential.",
    "s31": "Passport or ID Card Verification",
    "s32": "Read [Identification Document Requirements] for more details.",
    "s33": "Passport",
    "s34": "ID Card",
    "s35": "Upload Passport",
    "s36": "Upload ID Front Page",
    "s37": "Upload ID Back Page",
    "s38": "Uploading",
    "s39": "Upload Failed<br/>Please upload again",
    "s40": "Proof of Residence",
    "s41": "Upload",
    "s42": "Previous",
    "s43": "Next",
    "s44": "Only one step away from completion",
    "s45": "Proof of Residence Requirements",
    "s46": "File type：Utility Billy,or Bank / Credit card statement<br/>Valid document must contain：<br/>Full name<br/>Your address<br/>Less than 3 months old",
    "s47": "Passport or ID Card Requirements",
    "s48": "Valid document must contain：<br/>Colored photo<br/>Full name<br/>Date of birth<br/>Valid expiration date <br/>Official document number",
    "s49": "100%Completed Profile！",
    "s50": "Pending verification",
    "s51": "We will review it as soon as possible.",
    "s52": "Sorry!Verify failed!",
    "s53": "Edit",
    "s54": "Please verify your Email",
    "s55": "Please fill in your phone",
    "s56": "Please fill in your first name",
    "s57": "Please fill in your last name",
    "s58": "Please select your gender",
    "s59": "Please select your date of birth",
    "s60": "Please fill in your address",
    "s61": "Please fill in your city",
    "s62": "Please fill in your zip code",
    "s63": "Please select your country",
    "s64": "Please upload your passport",
    "s65": "Please upload your ID front page",
    "s66": "Please upload the ID back page",
    "s67": "Please upload proof of residence",
    "s68": "Please fill in  verification code",
    "s69": "Verification code is error",
    "s70": "Verified Successfully",
    "s71": "Please confirm that you have read and understood above questions.",
    "s72": "Please confirm that you I accept the Terms &Conditions, Privacy Policy and Risk Disclosure and Deposit&Withdrawal Policy",
    "s73": "Please select your country code",
    "s74": "Male",
    "s75": "Female",
    "s76": "Phone",
    "s77": "January",
    "s78": "February",
    "s79": "March",
    "s80": "April",
    "s81": "May",
    "s82": "June",
    "s83": "July",
    "s84": "August",
    "s85": "September",
    "s86": "October",
    "s87": "November",
    "s88": "December",
    "s89": "Email format is incorrect",
    "s90": "Now you can start trading now with up to USD 1000.",
    "s91": "upload proof of residence",
    "s7777": "name"
  }
}